# this was mostly a test endpoint and is not to be deployed

apiVersion: v1
kind: Endpoints
metadata:
  name: external-service
subsets:
  - addresses:
    - ip: 11.11.11.11
    - ip: 42.42.42.42
    ports:
    - port: 80