apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kavu
  labels:
    app: kavu
    tier: toptier
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: kavu
  template:
    metadata:
      labels:
        tier: kavu
    spec:
      containers:
      - name: kavubois
        image: jayharts1/kubia
